version: "3"
services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "48000:48000"
    working_dir: /root/projects/volume
    command: mkdocs serve
    volumes:
      - type: bind
        source: "./volume"
        target: "/root/projects/volume"

  nginx:
    image: nginx:latest
    ports:
      - "48080:80"
    volumes:
      - type: bind
        source: "./volume/site"
        target: "/usr/share/nginx/html"
        read_only: true
    depends_on:
      - mkdocs