name: deploy-mkdocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install mkdocs deps
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs \
            mkdocs-material \
            plantuml-markdown \
            python-markdown-math \
            pygments \
            pymdown-extensions \
            mkdocs-awesome-pages-plugin \
            mkdocs-autolinks-plugin \
            mkdocs-macros-plugin

      - name: build mkdocs for gh-pages
        run: |
          cd volume
          mkdocs build --clean --site-dir mkdocs

      - name: deploy to gh-pages under docs/mkdocs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: volume/mkdocs
          destination_dir: docs/mkdocs
          force_orphan: true